"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log('hello world');
let message = 'hello world';
// message = [];
let messageTwo;
messageTwo = 'hello there';
let arr = [1, 2, 3];
arr.push(4);
arr.push('hello');
